#!/usr/bin/env php
<?php
/**
 * aabc console bootstrap file.
 *
 * @link http://www.aabcframework.com/
 * @copyright Copyright (c) 2008 aabc Software LLC
 * @license http://www.aabcframework.com/license/
 */

defined('AABC_DEBUG') or define('AABC_DEBUG', false);
defined('AABC_ENV') or define('AABC_ENV', 'prod');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/aabcsoft/aabc2/Aabc.php');
require(__DIR__ . '/common/config/bootstrap.php');
require(__DIR__ . '/console/config/bootstrap.php');

$config = aabc\helpers\ArrayHelper::merge(
    require(__DIR__ . '/common/config/main.php'),
    require(__DIR__ . '/common/config/main-local.php'),
    require(__DIR__ . '/console/config/main.php'),
    require(__DIR__ . '/console/config/main-local.php')
);

$application = new aabc\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
